-- HBA scheduler — Phase 2 (proposed schedule storage)
--
-- How to apply: paste into the Supabase SQL editor and run. Idempotent.
--
-- Depends on 0002-sis-core.sql (terms, courses, profiles, students) and
-- 0007-scheduling.sql (student_course_requests).
--
-- Tables introduced:
--   schedule_drafts
--     One row per "proposal" generated by the solver. Header info: which
--     term, who generated it, score, status (proposed/reviewed/committed/
--     discarded), and a summary jsonb for solver telemetry + warnings.
--
--   schedule_draft_sections
--     Mirrors course_sections shape: (course, term, teacher, period,
--     section_code, room, modality, max_enrollment). Tied to a draft. When
--     a draft is committed, these rows are copied into course_sections.
--
--   schedule_draft_assignments
--     Per (draft_section, student) row. Mirrors enrollments. Stores the
--     fulfilled_request_id so the review UI can show "this assignment
--     satisfies student X's 2nd-choice elective request".

begin;

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- schedule_drafts
-- ---------------------------------------------------------------------------

create table if not exists schedule_drafts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  term_id uuid not null references terms(id) on delete cascade,
  created_by text,

  -- Lifecycle. proposed = solver just generated; reviewed = admin opened
  -- it; committed = admin clicked Commit and the rows were copied to
  -- course_sections + enrollments; discarded = admin marked it dead.
  status text not null default 'proposed'
    check (status in ('proposed','reviewed','committed','discarded')),

  -- Solver's score. Higher = better. Used to compare candidate drafts.
  score numeric(10,2),

  -- Solver telemetry. Recommended shape:
  --   { fulfilled_requests, unfulfilled_requests, warnings: [...],
  --     section_count, teachers_used, ... }
  -- Stored loosely so the solver can evolve without a schema change.
  summary jsonb not null default '{}'::jsonb,

  notes text
);

create index if not exists schedule_drafts_term_idx on schedule_drafts(term_id);
create index if not exists schedule_drafts_status_idx on schedule_drafts(status);

drop trigger if exists schedule_drafts_updated_at on schedule_drafts;
create trigger schedule_drafts_updated_at
before update on schedule_drafts
for each row
execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- schedule_draft_sections
-- ---------------------------------------------------------------------------

create table if not exists schedule_draft_sections (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),

  draft_id uuid not null references schedule_drafts(id) on delete cascade,
  course_id uuid not null references courses(id) on delete restrict,
  teacher_profile_id uuid references profiles(id) on delete set null,

  section_code text,

  -- Mirrors course_sections.period enum so we can copy 1:1 on commit.
  period text check (
    period is null
    or period in (
      'period_1','period_2','period_3','period_4','period_5','period_6',
      'elective_1','elective_2','async'
    )
  ),
  room text,

  max_enrollment integer check (max_enrollment is null or max_enrollment > 0),

  modality text not null default 'in_person'
    check (modality in ('in_person','online_async','online_sync','hybrid')),

  notes text
);

create index if not exists schedule_draft_sections_draft_idx
  on schedule_draft_sections(draft_id);
create index if not exists schedule_draft_sections_course_idx
  on schedule_draft_sections(course_id);

-- ---------------------------------------------------------------------------
-- schedule_draft_assignments
-- ---------------------------------------------------------------------------

create table if not exists schedule_draft_assignments (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),

  draft_section_id uuid not null references schedule_draft_sections(id) on delete cascade,
  student_id uuid not null references students(id) on delete cascade,

  -- Which request this assignment satisfies (or null for a student admin
  -- assigned manually who hadn't requested the course).
  fulfilled_request_id uuid references student_course_requests(id) on delete set null,

  unique (draft_section_id, student_id)
);

create index if not exists schedule_draft_assignments_section_idx
  on schedule_draft_assignments(draft_section_id);
create index if not exists schedule_draft_assignments_student_idx
  on schedule_draft_assignments(student_id);

commit;
