// lib/stripe.ts
//
// Server-side Stripe client + helpers. Used by:
//   - app/api/stripe/webhook/route.ts    (verify + handle payment events)
//   - app/apply/success/page.tsx          (optional defensive session lookup
//                                          in case the webhook is delayed)
//
// Two env vars, both required when Stripe integration is live:
//   STRIPE_SECRET_KEY      Live secret key (sk_live_...). Tenant-aware via
//                          lib/env.ts so HBA's deployment uses HBA's
//                          account; PCI uses its own once configured.
//   STRIPE_WEBHOOK_SECRET  Signing secret for the webhook endpoint
//                          (whsec_...). Generated by Stripe when you add
//                          the endpoint in the dashboard.
//
// Either name accepts the school-prefixed pattern (HBA_STRIPE_*) via the
// readSchoolEnv helper, same as the other school-aware vars.

import Stripe from "stripe"

function readSchoolEnv(canonical: string): string | undefined {
  // Inline mini-version of lib/env.ts readSchoolEnv to avoid a circular
  // import (lib/env imports lib/site, which doesn't import this — but
  // keeping stripe self-contained makes future moves easier).
  const direct = process.env[canonical]
  if (direct) return direct
  const school = process.env.SCHOOL_KEY?.trim().toLowerCase() ?? "hba"
  const prefix = school.toUpperCase()
  return process.env[`${prefix}_${canonical}`]
}

export function getStripeSecretKey(): string | undefined {
  return readSchoolEnv("STRIPE_SECRET_KEY")
}

export function getStripeWebhookSecret(): string | undefined {
  return readSchoolEnv("STRIPE_WEBHOOK_SECRET")
}

let cached: Stripe | null = null

export function getStripeClient(): Stripe {
  if (cached) return cached
  const key = getStripeSecretKey()
  if (!key) {
    throw new Error(
      "STRIPE_SECRET_KEY is not configured (also tried HBA_STRIPE_SECRET_KEY / PCI_STRIPE_SECRET_KEY)."
    )
  }
  cached = new Stripe(key)
  return cached
}
