import Link from "next/link"
import { redirect } from "next/navigation"
import { auth } from "@/auth"
import { createClient } from "@supabase/supabase-js"
import { getProfileByEmail } from "@/lib/sis"
import {
  listConferenceEvents,
  listSlotsForTeacher,
  type ConferenceEvent,
} from "@/lib/conferences"

export const dynamic = "force-dynamic"

const pacific = "America/Los_Angeles"
function formatTimestamp(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: pacific,
  }).format(new Date(value))
}

export default async function FacultyConferencesPage() {
  const session = await auth()
  if (!session?.user?.email) redirect("/admin/sign-in")
  const profile = await getProfileByEmail(session.user.email)
  if (!profile) redirect("/admin/sign-in")
  const isAdmin = session.isAdmin === true
  if (!isAdmin && !profile.roles.includes("faculty")) redirect("/admin/sign-in")

  const events = await listConferenceEvents({ activeOnly: true })

  // Slots per event for this teacher only.
  const slotsByEvent: Array<{
    event: ConferenceEvent
    slots: Awaited<ReturnType<typeof listSlotsForTeacher>>
  }> = []
  for (const ev of events) {
    slotsByEvent.push({
      event: ev,
      slots: await listSlotsForTeacher(ev.id, profile.id),
    })
  }

  // Pull student names for booked slots.
  const studentIds = new Set<string>()
  for (const { slots } of slotsByEvent) {
    for (const s of slots) {
      if (s.booked_for_student_id) studentIds.add(s.booked_for_student_id)
    }
  }
  const studentMap = new Map<string, string>()
  if (studentIds.size > 0) {
    const supabase = createClient(
      process.env.HBA_SUPABASE_URL!,
      process.env.HBA_SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    )
    const { data } = await supabase
      .from("students")
      .select("id, legal_first_name, legal_last_name, preferred_name")
      .in("id", [...studentIds])
      .returns<
        Array<{
          id: string
          legal_first_name: string
          legal_last_name: string
          preferred_name: string | null
        }>
      >()
    for (const s of data ?? []) {
      const display = s.preferred_name?.trim()
        ? `${s.preferred_name} ${s.legal_last_name}`
        : `${s.legal_first_name} ${s.legal_last_name}`
      studentMap.set(s.id, display)
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <Link
          href="/faculty-portal"
          className="text-sm font-semibold text-brand-navy underline-offset-4 hover:underline"
        >
          ← Back to faculty portal
        </Link>
      </div>

      <header className="space-y-2">
        <p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-orange">
          Conferences
        </p>
        <h1 className="text-3xl font-extrabold text-brand-navy sm:text-4xl">
          Your conference schedule
        </h1>
        <p className="text-sm text-slate-600">
          Slots are auto-generated by the office. Parents book through the
          family portal; you&rsquo;ll see new bookings here as they come in.
        </p>
      </header>

      {events.length === 0 ? (
        <section className="rounded-[2rem] border border-dashed border-slate-300 bg-white px-8 py-12 text-center text-slate-600 shadow-sm">
          No active conference events right now.
        </section>
      ) : (
        slotsByEvent.map(({ event, slots }) => {
          const booked = slots.filter(
            (s) => s.booked_by_parent_email && !s.cancelled_at
          )
          const open = slots.filter(
            (s) => !s.booked_by_parent_email && !s.cancelled_at
          )

          return (
            <section
              key={event.id}
              className="space-y-4 rounded-[2rem] border border-slate-200 bg-white px-6 py-6 shadow-sm"
            >
              <div>
                <h2 className="text-xl font-extrabold text-brand-navy">{event.name}</h2>
                <p className="text-xs text-slate-500">
                  {booked.length} booked · {open.length} open
                </p>
              </div>

              {slots.length === 0 ? (
                <p className="text-sm text-slate-600">
                  No slots generated for you yet. Ask the office to generate
                  slots for this event.
                </p>
              ) : (
                <ul className="space-y-2">
                  {slots.map((s) => {
                    const bookedFor = s.booked_for_student_id
                      ? studentMap.get(s.booked_for_student_id) ?? "(unknown student)"
                      : null
                    const isBooked = !!s.booked_by_parent_email && !s.cancelled_at
                    return (
                      <li
                        key={s.id}
                        className={`rounded-2xl border px-4 py-3 ${
                          isBooked
                            ? "border-emerald-200 bg-emerald-50/60"
                            : "border-slate-200 bg-slate-50"
                        }`}
                      >
                        <div className="grid gap-2 sm:grid-cols-[minmax(0,200px)_minmax(0,1fr)] sm:items-center">
                          <p className="text-sm font-semibold text-slate-900">
                            {formatTimestamp(s.start_at)}
                          </p>
                          {isBooked ? (
                            <div className="text-xs text-slate-700">
                              <p>
                                <strong className="font-semibold">{bookedFor}</strong> —{" "}
                                {s.booked_by_parent_email}
                              </p>
                              {s.parent_notes && (
                                <p className="mt-1 text-slate-600 whitespace-pre-wrap">
                                  Notes: {s.parent_notes}
                                </p>
                              )}
                            </div>
                          ) : (
                            <span className="text-xs text-slate-500">Open</span>
                          )}
                        </div>
                      </li>
                    )
                  })}
                </ul>
              )}
            </section>
          )
        })
      )}
    </div>
  )
}
